---
- name: Copy hasp files
  copy:
    src: "{{ item }}"
    dest: /tmp/
  with_fileglob:
    - hasp/aksusbd*

- name: Find rpm files in /tmp folder
  find:
     paths: "/tmp"
     pattern: "aksusbd*.rpm"
  register: rpm_files

- set_fact:
    rpm_list: "{{ rpm_files.files | map(attribute='path') | list}}"

- name: Install rpms
  yum:
    name: "{{ rpm_list }}"
    state: present

- name: Delete rpms
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ rpm_list }}"
